name: Publish Package

on:
  push:
    branches:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'zulu'
          
      - name: Ensure Settings File Permissions
        run: chmod 600 .github/workflows/settings.xml

      - name: Grant execute permission to Maven Wrapper
        run: chmod +x ./mvnw

      - name: Publish Package
        run: ./mvnw deploy -s .github/workflows/settings.xml -X
        env:
          GITHUB_TOKEN: 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
          GITHUB_ACTOR: rajeshchettupalli-achala
